### ISSUE TITLE
Ratatui

### ISSUE THREAD

**Issue by joshka** [pierreyoda/hncli#1]
Hey, I saw your hn post. Come check out ratatui, a well maintained fork of tui-rs.
- https://ratatui.rs/ 
- https://github.com/ratatui/ratatui
- https://discord.com/invite/pMCEU9hNEj
- https://forum.ratatui.rs/ (fairly new, low traffic so far)

**Comment by pierreyoda** [comment]
Hi @joshka , thanks for reminding me of this, here's the merged PR: https://github.com/pierreyoda/hncli/pull/2

**Comment by joshka** [comment]
Looks like it went pretty smoothly :)

**Comment by joshka** [comment]
Hi there, just a quick thing. I declined the invite to be added as a collaborator to this repo as I have enough on my plate right now. Thank you though. I look forward to seeing how this goes.

**Comment by pierreyoda** [comment]
Hi joshka, no problems thanks! I think I'll see with the ratatui Discord.
